### ISSUE TITLE
Not charging up to expected SOC

### ISSUE THREAD

**Issue by doncuco** [sonnen-tools/node-red#21]
I had the issue, that the battery is not charging to my expected issue a few days now.

I See that the log tells that there are 21

<img width="1166" alt="image" src="https://github.com/sonnen-tools/node-red/assets/122402791/c321c531-5eee-4a15-82b0-0a28f976f4f5">
<img width="576" alt="image" src="https://github.com/sonnen-tools/node-red/assets/122402791/39cefe90-cc20-4fde-b5bf-1c459e9e2417">

<img width="576" alt="image" src="https://github.com/sonnen-tools/node-red/assets/122402791/0e292a7e-f870-4687-9f62-9eac30180c77">

**Comment by markusjnagel** [comment]
Hi Tobias @doncuco - you could be hitting this issue https://github.com/sonnen-tools/node-red/issues/6 which I have fixed partly in 0.0.3-WIP but fully in 0.0.4-WIP (which I haven't released yet, sorry... will do on or after next Thursday).

If you check the issue I linked above, you could maybe verify if you hit an error (I documented what I did to isolate the error there). Or, just wait until 0.0.4 is released and retry then.

Regarding the "charged" - yeah, I know that this value is unrealistic, I also see higher values than what my battery capacity is... I take this value from the Sonnenbatterie's `RemainingCapacity_Wh` - but for our purposes, it doesn't matter if it is WattHours or apples, oranges.... as long as it is consistent. 

I save the value when I start charging and calculate the difference between the saved value and the actual value when I stop charging. So, I get what has been charged. 
I use that value in the chargeLog, so I calculate the cost by amount charged. 
1000 Wh = 1kWh at 0.30EUR/kWh = 0.30EUR. 
2000 Wh = 2kWh at 0.20EUR/kWh = 0.40EUR. 
Cost per kWh in the battery: Total Cost / Total Charge =  0.70EUR / 3kWh  =  0.2333EUR/kWh. 

As long as whatever the SB counts is consistent, it doesn't matter - since the relative measure counts. If you multiply both "charges" from the above example with e.g. 2.34567 - you still get the same cost per kWh: 

2345.67 Wh = 2.34567 kWh at 0.30EUR/kWh = 0.703701EUR
4691.34 Wh = 4.69134 kWh at 0.20EUR/kWh = 0.938268 EUR

Total Cost / Total Charge = 1.641969 EUR / 7.03701 kWh = 0.2333 EUR/kWh

**Comment by doncuco** [comment]
Hi Markus,
any updates on that? I am still having this issue. Checked the calculation and could not understand that it does not work because, as you told it uses raminingcapacity and the starting capacity. So probably it should work. 
I am still on version 0.0.2 is 0.0.3-WIP or 0.0.4 soon ready to use?

**Comment by doncuco** [comment]
So 0.0.3 didn't fix the issue for me. The script thinks it loaded 24kW.
![image](https://github.com/user-attachments/assets/727ab44b-6f3f-47ff-8865-c7339591f278)

But the battery loaded only to 63%. 
![image](https://github.com/user-attachments/assets/8d738a57-0656-4deb-8b42-a00189e28f8a)
